language: node_js
node_js:
- node
deploy:
  provider: npm
  email: schenk@devbros.de
  api_key:
    secure: Z0FRTZpf/iOb5wMPjtT7+r4EBkeaKi3q7JQZtw62+1OhnKNtFP4XE4rzq4cIdef1mCWrUlKLa/Eghl+Hw3T1rXtlYBCcIK5X8RzXCLFRfyfuqYzqWCmJtkoRKN3fQUHNsdzILlF84OyrXFq6SDZjUOS8e9CI2fRET7OX/F9/dp0E6ZOnADWN5q+OAboQuJ+EGGXUscmcLZCa50IxcxvsaSg4A7TuWG8zFE7g19TRPxbRESjeWfAggomGdKVLyz/0ygMvYew3bpZtkUKQHftZSt7OvYFCVKKG12eBuYhZNlmlRPia6+B9kFFD9348CINOxvRZ4Sh+KU2Hgg/J8nHHjdjx6cl9NcS/HJweGJwplTbe3P6jSGSRXmUdGi0p6ISxfYyYlUTtka9uRCeP0fZnhjMYu0PsorB6Jr36W1uJgCRsl2CPen073emlhSY+GO9BONXeMRGMOMm/Sr4mw2LXlJosxqnAs3Z6WW3pAi2EDiSmrEBeHH/zbA2udI+4NszJ7AcMpSiAAPRL5ycr7UEkIvNvv4Rp3XsDPMjCC5nJ2O8IwzP/0ue6haYb9J0g/H/BfYliBlBn9lbfEmmWDsr0Ay5gGoBmypZbet3Hx6FLc8hjcEAYWE+r3pfebjDYBYwCglQX9Eeiph6cMm4Xb3LDkZv1uWH0bk02RcjKjFNs6Jg=
  on:
    tags: true
    repo: DaniSchenk/moment-feiertage
    branch: master
